sudo: required
services:
 - docker

before_install:
 - docker build -f Dockerfile.dev -t scaff101/docker-react:latest .

script:
 - docker run scaff101/docker-react npm run test -- --coverage
